fix build

diff --git a/scripts/build-on-push-tail b/scripts/build-on-push-tail
--- a/scripts/build-on-push-tail
+++ b/scripts/build-on-push-tail
@@ -66,4 +66,15 @@
       - name: Push To Docker Hub
         shell: bash
         run: |
-          go run main.go push --app=${{ matrix.APP }} --tag=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/ --tag-to docker.io/zcube/bitnami-compat- --dest-creds=zcube:${{ secrets.DOCKER_HUB_KEY }}
+          set -euo pipefail
+          n=0
+          until [ "$n" -ge 5 ] # retry 5 times
+          do
+            go run main.go push --app=${{ matrix.APP }} --tag=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/ --tag-to docker.io/zcube/bitnami-compat- --dest-creds=zcube:${{ secrets.DOCKER_HUB_KEY }} && break
+            n=$((n+1)) 
+            sleep 15
+          done
+          if [ "$n" -ge 5 ]; then
+            echo "Failed after 5 attempts!"
+            exit 1
+          fi
